/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmbientBackground: typeof import('./src/components/common/AmbientBackground.vue')['default']
    AmbientOrb: typeof import('./src/components/onboarding/AmbientOrb.vue')['default']
    AudioPlayer: typeof import('./src/components/common/AudioPlayer.vue')['default']
    BackgroundScanStatus: typeof import('./src/components/library/BackgroundScanStatus.vue')['default']
    CategoryTree: typeof import('./src/components/library/CategoryTree.vue')['default']
    DawGuide: typeof import('./src/components/library/DawGuide.vue')['default']
    DawStep: typeof import('./src/components/onboarding/DawStep.vue')['default']
    GridBackground: typeof import('./src/components/onboarding/GridBackground.vue')['default']
    LibraryBrowser: typeof import('./src/components/library/LibraryBrowser.vue')['default']
    LibraryConfig: typeof import('./src/components/library/LibraryConfig.vue')['default']
    LibrarySidebar: typeof import('./src/components/library/LibrarySidebar.vue')['default']
    LibraryStats: typeof import('./src/components/library/LibraryStats.vue')['default']
    ProgressBar: typeof import('./src/components/common/ProgressBar.vue')['default']
    ReadyStep: typeof import('./src/components/onboarding/ReadyStep.vue')['default']
    ResultStep: typeof import('./src/components/onboarding/ResultStep.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SampleList: typeof import('./src/components/library/SampleList.vue')['default']
    ScanProgress: typeof import('./src/components/common/ScanProgress.vue')['default']
    ScanStep: typeof import('./src/components/onboarding/ScanStep.vue')['default']
    SettingsPanel: typeof import('./src/components/library/SettingsPanel.vue')['default']
    SourceManager: typeof import('./src/components/library/SourceManager.vue')['default']
    StepDots: typeof import('./src/components/onboarding/StepDots.vue')['default']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._7swpny55abm4jmsp7z6w3k5f4u/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_48d9005fb25bd4bad797a895a641d048/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._7swpny55abm4jmsp7z6w3k5f4u/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._7swpny55abm4jmsp7z6w3k5f4u/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_48d9005fb25bd4bad797a895a641d048/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._7swpny55abm4jmsp7z6w3k5f4u/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._7swpny55abm4jmsp7z6w3k5f4u/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UpdateNotification: typeof import('./src/components/UpdateNotification.vue')['default']
    UProgress: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._7swpny55abm4jmsp7z6w3k5f4u/node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USelect: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._7swpny55abm4jmsp7z6w3k5f4u/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USwitch: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._7swpny55abm4jmsp7z6w3k5f4u/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UToaster: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._7swpny55abm4jmsp7z6w3k5f4u/node_modules/@nuxt/ui/dist/runtime/components/Toaster.vue')['default']
    UTooltip: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._7swpny55abm4jmsp7z6w3k5f4u/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
    WelcomeStep: typeof import('./src/components/onboarding/WelcomeStep.vue')['default']
  }
}
