/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmbientOrb: typeof import('./src/components/onboarding/AmbientOrb.vue')['default']
    AudioPlayer: typeof import('./src/components/common/AudioPlayer.vue')['default']
    CategoryTree: typeof import('./src/components/library/CategoryTree.vue')['default']
    ProgressBar: typeof import('./src/components/common/ProgressBar.vue')['default']
    ResultStep: typeof import('./src/components/onboarding/ResultStep.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SampleList: typeof import('./src/components/library/SampleList.vue')['default']
    ScanStep: typeof import('./src/components/onboarding/ScanStep.vue')['default']
    SourcesStep: typeof import('./src/components/onboarding/SourcesStep.vue')['default']
    StepDots: typeof import('./src/components/onboarding/StepDots.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._ucxs7xf2jflveb54ionsknatxq/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._ucxs7xf2jflveb54ionsknatxq/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._ucxs7xf2jflveb54ionsknatxq/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCheckbox: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._ucxs7xf2jflveb54ionsknatxq/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._ucxs7xf2jflveb54ionsknatxq/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UpdateNotification: typeof import('./src/components/UpdateNotification.vue')['default']
    UProgress: typeof import('./node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._ucxs7xf2jflveb54ionsknatxq/node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    WelcomeStep: typeof import('./src/components/onboarding/WelcomeStep.vue')['default']
  }
}
