/// Classification rules mapping keywords to categories.
///
/// Keywords are matched against a normalized string where all non-alphanumeric chars
/// are replaced by spaces and the whole string is padded with spaces on both sides.
/// This allows word-boundary-aware matching by padding short/ambiguous keywords
/// with spaces (e.g., `" hh "` only matches the standalone token "hh").
pub struct ClassificationRule {
    pub category: &'static str,
    pub keywords: &'static [&'static str],
    pub color: &'static str,
}

pub const RULES: &[ClassificationRule] = &[
    // --- Drums (#ff6b35) ---
    ClassificationRule {
        category: "kick",
        keywords: &[
            "kick",
            " kck ",
            " kik ",
            "bass drum",
            "bassdrum",
            "kickdrum",
            " bd ",
        ],
        color: "#ff6b35",
    },
    ClassificationRule {
        category: "snare",
        keywords: &["snare", " snr ", "rimshot", "snappy", " sd "],
        color: "#ff6b35",
    },
    ClassificationRule {
        category: "hihat",
        keywords: &[
            "hihat",
            "hi hat",
            "hi-hat",
            " hh ",
            " hat ",
            "closed hat",
            "open hat",
            "pedal hat",
        ],
        color: "#ff6b35",
    },
    ClassificationRule {
        category: "clap",
        keywords: &["clap", " clp ", "handclap", "snap clap", " snap "],
        color: "#ff6b35",
    },
    ClassificationRule {
        category: "tom",
        keywords: &[
            " tom ",
            "tom tom",
            "floor tom",
            "rack tom",
            "high tom",
            "mid tom",
            "low tom",
        ],
        color: "#ff6b35",
    },
    ClassificationRule {
        category: "cymbal",
        keywords: &["cymbal", "crash", "ride cymbal", "splash", "china cymbal"],
        color: "#ff6b35",
    },
    ClassificationRule {
        category: "perc",
        keywords: &[
            "perc",
            "percussion",
            "shaker",
            "tambourine",
            " tamb ",
            "conga",
            "bongo",
            "cowbell",
            "woodblock",
            "cajon",
            "maraca",
            "agogo",
            "cabasa",
            "triangle",
            "clave",
            "rim shot",
            "rimclick",
            " rim ",
            "timbale",
            "djembe",
            "guiro",
            "vibraslap",
            "bell tree",
            "wind chime",
        ],
        color: "#ff6b35",
    },
    // --- Bass (#ef4444) ---
    ClassificationRule {
        category: "bass",
        keywords: &[
            "bass",
            "808",
            "sub bass",
            "subbass",
            "bassline",
            "reese",
            " bas ",
            "deep bass",
        ],
        color: "#ef4444",
    },
    // --- Melodic (#4ade80) ---
    ClassificationRule {
        category: "keys",
        keywords: &[
            "piano",
            "keys",
            "keyboard",
            "rhodes",
            "wurlitzer",
            "electric piano",
            "epiano",
            " ep ",
            "clavinet",
            "organ",
            "harpsichord",
            "celesta",
            "marimba",
            "vibraphone",
            "xylophone",
            "glockenspiel",
            "kalimba",
            "music box",
            "musicbox",
            "melodica",
        ],
        color: "#4ade80",
    },
    ClassificationRule {
        category: "pad",
        keywords: &[
            "pad",
            "atmosphere",
            "atmo",
            "ambient",
            "texture",
            "drone",
            "sustain pad",
            "evolving",
            "cinematic",
        ],
        color: "#4ade80",
    },
    ClassificationRule {
        category: "lead",
        keywords: &[
            "lead",
            "synth lead",
            "pluck",
            "mono lead",
            " synth ",
            "saw lead",
            "square lead",
        ],
        color: "#4ade80",
    },
    ClassificationRule {
        category: "arp",
        keywords: &[" arp ", "arpeggio", "arpeggiated", "sequence"],
        color: "#4ade80",
    },
    ClassificationRule {
        category: "chord",
        keywords: &["chord", "stab", " chrd ", "chords"],
        color: "#4ade80",
    },
    ClassificationRule {
        category: "guitar",
        keywords: &[
            "guitar",
            "gtr",
            "acoustic guitar",
            "electric guitar",
            "nylon",
            "strum",
            "fingerpick",
        ],
        color: "#4ade80",
    },
    ClassificationRule {
        category: "strings",
        keywords: &[
            "strings",
            "violin",
            "viola",
            "cello",
            "contrabass",
            "orchestral",
            "ensemble",
            "pizzicato",
            "spiccato",
        ],
        color: "#4ade80",
    },
    ClassificationRule {
        category: "brass",
        keywords: &[
            "brass",
            "trumpet",
            "trombone",
            "horn",
            "tuba",
            "french horn",
            "flugelhorn",
            "saxophone",
            " sax ",
        ],
        color: "#4ade80",
    },
    // --- Vocal (#f472b6) ---
    ClassificationRule {
        category: "vocal",
        keywords: &[
            "vocal",
            " vox ",
            "voice",
            "acapella",
            "adlib",
            "choir",
            "chant",
            "sing",
            "spoken",
            "whisper",
            "a capella",
            "harmony vocal",
            "backing vocal",
        ],
        color: "#f472b6",
    },
    // --- FX (#06b6d4) ---
    ClassificationRule {
        category: "fx",
        keywords: &[
            " fx ",
            " sfx ",
            "effect",
            "riser",
            "impact",
            "sweep",
            "downlift",
            "uplifter",
            "whoosh",
            "reverse",
            "transition",
            "swell",
            "buildup",
            "build up",
            "drop",
            "downer",
            "foley",
            "glitch",
            "stutter",
            "noise",
            "white noise",
            "tape stop",
        ],
        color: "#06b6d4",
    },
    // --- Loops (#818cf8) ---
    ClassificationRule {
        category: "loop",
        keywords: &[
            "loop",
            "drum loop",
            "melody loop",
            "bass loop",
            "full loop",
            "top loop",
            "groove",
            "break",
            "breakbeat",
            "pattern",
            "beat",
        ],
        color: "#818cf8",
    },
];
